### PR TITLE
feat: use webmap id as env variable

### PR DESCRIPTION
**Pull request by steveoh**
when we get a staging and production web map id we can update the variables

### CODE REVIEW

**Comment by stdavis** [comment]
I wonder if we are going to end up using more than one web map? I'm thinking that the overview web map might be different? Not sure.

**Comment by steveoh** [comment]
Ok, should we use this for now or remove it and wait to see what happens?

**Comment by stdavis** [comment]
I'm good either way. Just wanted to let you know my thoughts about what might happen in the future.

**Comment by steveoh** [comment]
Ok, since this is sort of a no op and has a 50% chance of working in the future, let's just merge it.

**Pull request merged**
